"""created match table

Revision ID: 58d60966769b
Revises: 20b4f2d21b1e
Create Date: 2025-12-05 11:07:03.790946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58d60966769b'
down_revision: Union[str, Sequence[str], None] = '20b4f2d21b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('home_logo', sa.String(), nullable=False),
    sa.Column('away_logo', sa.String(), nullable=False),
    sa.Column('kickoff', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('league', sa.String(), nullable=False),
    sa.Column('league_code', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('competition_logo', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_flag', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
