"""made some cols nullable

Revision ID: a162dec9008b
Revises: c14b719173f9
Create Date: 2025-12-05 14:32:14.767964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a162dec9008b'
down_revision: Union[str, Sequence[str], None] = 'c14b719173f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'home_team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('match', 'away_team',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('match', 'home_logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('match', 'away_logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'away_logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('match', 'home_logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('match', 'away_team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('match', 'home_team',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
