"""added api-based match id to match table

Revision ID: e8693b418af4
Revises: 58d60966769b
Create Date: 2025-12-05 11:13:03.252025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8693b418af4'
down_revision: Union[str, Sequence[str], None] = '58d60966769b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('api_match_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'match', ['id'])
    op.create_unique_constraint(None, 'match', ['api_match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='unique')
    op.drop_constraint(None, 'match', type_='unique')
    op.drop_column('match', 'api_match_id')
    # ### end Alembic commands ###
